import type { AiReport, AiReportDecision, AssistantInsightResponse } from "@/lib/api";
import type { ImportReportTableData } from "@/lib/import-report-data";
import { buildEquipmentCounterRows } from "@/lib/import-report-data";

type ReportFocus = "executive" | "risks" | "quality" | "full";

function rowCell(value: unknown) {
  return String(value ?? "—");
}

function appendTableSection(
  lines: string[],
  title: string,
  headers: string[],
  rows: Record<string, unknown>[],
  keys: string[],
  limit: number,
) {
  lines.push("", title, headers.join(" | "));
  rows.slice(0, limit).forEach((row) => {
    lines.push(keys.map((key) => rowCell(row[key])).join(" | "));
  });
  if (rows.length > limit) {
    lines.push(`… +${rows.length - limit} lignes`);
  }
}

function htmlTable(headers: string[], rows: Record<string, unknown>[], keys: string[], limit: number) {
  const head = headers.map((h) => `<th>${escapeHtml(h)}</th>`).join("");
  const body = rows
    .slice(0, limit)
    .map(
      (row) => `<tr>${keys.map((key) => `<td>${escapeHtml(rowCell(row[key]))}</td>`).join("")}</tr>`,
    )
    .join("");
  const more = rows.length > limit ? `<p class="table-note">… ${rows.length - limit} lignes supplementaires</p>` : "";
  return `<table class="data-table"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>${more}`;
}

function htmlBarChart(
  rows: Record<string, unknown>[],
  labelKey: string,
  valueKey: string,
  color: string,
  limit: number,
) {
  const slice = rows.slice(0, limit);
  const max = Math.max(1, ...slice.map((row) => Number(row[valueKey] ?? 0)));
  return slice
    .map((row) => {
      const label = rowCell(row[labelKey]);
      const value = Number(row[valueKey] ?? 0);
      return `<div class="chart-row"><span class="chart-label-wide">${escapeHtml(label)}</span><div class="chart-track"><div class="chart-bar" style="width:${Math.max(4, (value / max) * 100)}%;background:${color}"></div></div><span class="chart-value">${value}</span></div>`;
    })
    .join("");
}

const AI_FALLBACK_PATTERNS = [
  /j['']ai bien not[eé]/i,
  /pas encore de jeu de donn[eé]es/i,
  /pistes utiles/i,
  /reformulez librement/i,
  /i don't have a precise dataset/i,
  /here are some useful/i,
  /reformulate freely/i,
  /genere le rapport post-import/i,
  /generate the post-import report/i,
  /reponds uniquement/i,
  /reply only with/i,
];

export function isUsableAiReportMessage(raw: string): boolean {
  const text = stripNarratorWrapper(raw).trim();
  if (!text || text.length < 40) return false;
  if (AI_FALLBACK_PATTERNS.some((pattern) => pattern.test(text))) return false;
  if (text.startsWith("## ") || /\n## /.test(text)) return true;
  return text.length >= 120 && !/\*\*(Contexte actif|Votre question|Synthèse)\*\*/i.test(text);
}

function stripNarratorWrapper(raw: string): string {
  let text = raw.trim();
  if (!text) return "";

  const markdownStart = text.search(/^##\s/m);
  if (markdownStart > 0) {
    text = text.slice(markdownStart);
  } else {
    const inlineStart = text.indexOf("\n## ");
    if (inlineStart > 0) {
      text = text.slice(inlineStart + 1);
    }
  }

  text = text
    .replace(/\*\*Votre question\*\*[\s\S]*?(?=\n\n\*\*|\n##\s|$)/i, "")
    .replace(/\*\*Your question\*\*[\s\S]*?(?=\n\n\*\*|\n##\s|$)/i, "")
    .replace(/\*\*Contexte actif\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Active context\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Synthèse\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Summary\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Données\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Data\*\*[^\n]*\n?/gi, "")
    .replace(/\*\*Aperçu\*\*[\s\S]*?(?=\n\n\*\*|\n##\s|$)/gi, "")
    .replace(/\*\*Preview\*\*[\s\S]*?(?=\n\n\*\*|\n##\s|$)/gi, "")
    .replace(/\*\*Interprétation\*\*[\s\S]*?(?=\n\n\*_|$)/gi, "")
    .replace(/\*\*Interpretation\*\*[\s\S]*?(?=\n\n\*_|$)/gi, "")
    .replace(/\n_*Réponse générée par RAN Intelligence[\s\S]*_*\s*$/i, "")
    .replace(/\n_*Response generated by RAN Intelligence[\s\S]*_*\s*$/i, "")
    .trim();

  return text;
}

export function cleanAiReportMessage(raw: string): string {
  let text = stripNarratorWrapper(raw);
  if (!text) return "";

  const startMarkers = [
    "## Synthèse exécutive",
    "## Résumé exécutif",
    "## Executive summary",
    "## Analyse critique",
    "## Critical snapshot",
  ];
  for (const marker of startMarkers) {
    const idx = text.indexOf(marker);
    if (idx > 80) {
      text = text.slice(idx);
      break;
    }
  }

  text = text.replace(/\nR[ée]digez? en [\s\S]*$/i, "");
  text = text.replace(/\nWrite a premium [\s\S]*$/i, "");
  text = text.replace(/\nStructure:[\s\S]*$/i, "");
  text = text.replace(/\nStyle:[\s\S]*$/i, "");
  text = text.trim();

  if (!text || !isUsableAiReportMessage(text)) return "";
  return text;
}

export function buildReportExportText(
  fr: boolean,
  report: AiReport,
  aiInsight: AssistantInsightResponse | null,
  focus: ReportFocus,
  snapshotDate: string,
  tableData?: ImportReportTableData | null,
) {
  const lang = fr ? "fr" : "en";
  const aiText = aiInsight?.message ? cleanAiReportMessage(aiInsight.message) : "";
  const lines: string[] = [
    fr ? "RAPPORT POST-IMPORT RAN INTELLIGENCE" : "RAN INTELLIGENCE POST-IMPORT REPORT",
    `${fr ? "Snapshot" : "Snapshot"}: ${snapshotDate}`,
    `${fr ? "Genere" : "Generated"}: ${report.generated_at}`,
    `${fr ? "Focus" : "Focus"}: ${focus}`,
    `${fr ? "Indice de risque" : "Risk index"}: ${report.risk_index ?? 0}/100`,
    "",
    fr ? "RESUME EXECUTIF" : "EXECUTIVE SUMMARY",
    report.executive[lang],
    "",
    fr ? "ANALYSES CRITIQUES" : "CRITICAL FINDINGS",
  ];
  (report.critical_findings ?? []).forEach((item) => lines.push(`  [${item.severity.toUpperCase()}] ${item[lang]}`));
  lines.push("", fr ? "RECOMMANDATIONS DECISIONNELLES" : "DECISION RECOMMENDATIONS");
  (report.decisions ?? []).forEach((item: AiReportDecision) => lines.push(`  ${item.priority} — ${item[lang]}`));
  if (aiText) {
    lines.push("", fr ? "ANALYSE IA" : "AI ANALYSIS", aiText);
  }
  report.sections.forEach((section) => {
    lines.push("", section.title[lang].toUpperCase());
    section.lines[lang].forEach((line) => lines.push(`  - ${line}`));
  });

  if (tableData) {
    appendTableSection(
      lines,
      fr ? "TABLE SITES" : "SITES TABLE",
      ["site_id", "site_name", "site_state", "nb_cells", "technologies"],
      tableData.sitesRows,
      ["site_id", "site_name", "site_state", "nb_cells", "technologies"],
      25,
    );
    appendTableSection(
      lines,
      fr ? "TABLE INVENTAIRE (compteur top 7)" : "INVENTORY TABLE (top 7 counter)",
      ["snapshot_date", "site_id", "object_type", "compteur"],
      buildEquipmentCounterRows(tableData.inventoryRows, 7),
      ["snapshot_date", "site_id", "object_type", "compteur"],
      7,
    );
    appendTableSection(
      lines,
      fr ? "TABLE ASSETS (codes produit)" : "ASSETS TABLE (product codes)",
      ["product_code", "serial_count"],
      tableData.assetsPivotRows,
      ["product_code", "serial_count"],
      20,
    );
  }
  return lines.join("\n");
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function severityColor(level: string) {
  const normalized = level.toLowerCase();
  if (normalized.includes("crit")) return "#dc2626";
  if (normalized.includes("high") || normalized.includes("eleve")) return "#ea580c";
  if (normalized.includes("med") || normalized.includes("moy")) return "#d97706";
  return "#64748b";
}

function htmlSectionBlock(title: string, body: string, pageBreak = false) {
  return `<section class="block${pageBreak ? " page-break" : ""}"><h2 class="section-title">${escapeHtml(title)}</h2>${body}</section>`;
}

function htmlInsightCards(sections: AiReport["sections"], lang: "fr" | "en") {
  if (!sections.length) return "";
  return `<div class="insight-grid">${sections
    .map(
      (section) =>
        `<article class="insight-card"><h3>${escapeHtml(section.title[lang])}</h3><ul>${section.lines[lang].map((line) => `<li>${escapeHtml(line)}</li>`).join("")}</ul></article>`,
    )
    .join("")}</div>`;
}

export function openStyledReportPdf(
  fr: boolean,
  report: AiReport,
  aiInsight: AssistantInsightResponse | null,
  focus: ReportFocus,
  snapshotDate: string,
  severityChart: { level: string; count: number }[],
  tableData?: ImportReportTableData | null,
) {
  const lang = fr ? "fr" : "en";
  const aiText = aiInsight?.message ? cleanAiReportMessage(aiInsight.message) : "";
  const riskScore = report.risk_index ?? 0;
  const riskColor = riskScore >= 70 ? "#dc2626" : riskScore >= 40 ? "#ea580c" : "#64748b";
  const m = report.metrics;
  const equipmentCount = tableData?.inventoryRows.length ?? 0;

  const kpiItems = [
    { label: fr ? "Sites" : "Sites", value: m.total_sites ?? tableData?.sitesRows.length ?? 0 },
    { label: fr ? "Equipements" : "Equipment", value: equipmentCount },
    { label: fr ? "Alertes" : "Alerts", value: m.anomalies_total ?? 0 },
    { label: fr ? "Critiques" : "Critical", value: m.anomalies_critical ?? 0 },
    { label: fr ? "Bloques" : "Blocked", value: m.blocked_sites ?? 0 },
  ];

  const maxSeverity = Math.max(1, ...severityChart.map((row) => row.count));
  const equipmentRows = tableData ? buildEquipmentCounterRows(tableData.inventoryRows, 7) : [];

  const decisionsHtml =
    (report.decisions ?? []).length > 0
      ? (report.decisions ?? [])
          .map((item) => {
            const cls = item.priority === "P1" ? "p1" : item.priority === "P2" ? "p2" : "p3";
            return `<div class="decision"><span class="priority ${cls}">${escapeHtml(item.priority)}</span><div><span class="decision-cat">${escapeHtml(item.category)}</span><p>${escapeHtml(item[lang])}</p></div></div>`;
          })
          .join("")
      : "";

  const findingsHtml =
    (report.critical_findings ?? []).length > 0
      ? (report.critical_findings ?? [])
          .map((item) => `<div class="finding"><strong>${escapeHtml(item.severity.toUpperCase())}</strong> ${escapeHtml(item[lang])}</div>`)
          .join("")
      : "";

  const severityHtml = severityChart.length
    ? severityChart
        .map(
          (row) =>
            `<div class="chart-row"><span class="chart-label">${escapeHtml(String(row.level))}</span><div class="chart-track"><div class="chart-bar" style="width:${Math.max(8, (row.count / maxSeverity) * 100)}%;background:${severityColor(String(row.level))}"></div></div><span class="chart-value">${row.count}</span></div>`,
        )
        .join("")
    : "";

  const siteChartRows = (tableData?.sitesRows ?? []).slice(0, 7).map((row) => ({
    site_name: String(row.site_name ?? row.site_id ?? "?"),
    nb_cells: Number(row.nb_cells ?? 0),
  }));

  const dataSections = tableData
    ? [
        htmlSectionBlock(
          fr ? "1 · Sites" : "1 · Sites",
          `<p class="chart-caption">${fr ? "Cellules par site" : "Cells per site"}</p><div class="chart-panel">${htmlBarChart(siteChartRows, "site_name", "nb_cells", "#64748b", 7)}</div>${htmlTable(
            fr ? ["Date snapshot", "ID site", "Nom site", "Etat", "Cellules", "Technologies"] : ["Snapshot", "Site ID", "Site name", "State", "Cells", "Technologies"],
            tableData.sitesRows,
            ["snapshot_date", "site_id", "site_name", "site_state", "nb_cells", "technologies"],
            tableData.sitesRows.length,
          )}`,
        ),
        htmlSectionBlock(
          fr ? "2 · Inventaire equipements" : "2 · Equipment inventory",
          `<p class="chart-caption">${fr ? "Equipements par type" : "Equipment by type"}</p><div class="chart-panel">${htmlBarChart(tableData.charts.byType.slice(0, 7), "object_type", "total_equipment", "#dc2626", 7)}</div>${htmlTable(
            fr ? ["Date snapshot", "ID site", "Type equipement", "Compteur"] : ["Snapshot", "Site ID", "Equipment type", "Counter"],
            equipmentRows,
            ["snapshot_date", "site_id", "object_type", "compteur"],
            7,
          )}`,
          true,
        ),
        htmlSectionBlock(
          fr ? "3 · Assets (codes produit)" : "3 · Assets (product codes)",
          `<p class="chart-caption">${fr ? "Top codes produit" : "Top product codes"}</p><div class="chart-panel">${htmlBarChart(
            tableData.assetsPivotRows.slice(0, 7).map((row) => ({ product_code: row.product_code, serial_count: row.serial_count })),
            "product_code",
            "serial_count",
            "#7c3aed",
            7,
          )}</div>${htmlTable(
            fr ? ["Code produit", "Nb n° serie"] : ["Product code", "Serial count"],
            tableData.assetsPivotRows,
            ["product_code", "serial_count"],
            tableData.assetsPivotRows.length,
          )}`,
          true,
        ),
      ].join("")
    : "";

  const html = `<!DOCTYPE html>
<html lang="${fr ? "fr" : "en"}">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(fr ? "Rapport post-import RAN Intelligence" : "RAN Intelligence post-import report")}</title>
  <style>
    @page { size: A4; margin: 14mm; }
    * { box-sizing: border-box; }
    body { font-family: "Segoe UI", Arial, sans-serif; color: #0f172a; margin: 0; padding: 0; background: #fff; font-size: 12px; line-height: 1.45; }
    .doc { max-width: 780px; margin: 0 auto; }
    .hero { padding: 0 0 18px; border-bottom: 3px solid #dc2626; margin-bottom: 18px; }
    .eyebrow { font-size: 9px; font-weight: 700; letter-spacing: .2em; text-transform: uppercase; color: #dc2626; }
    h1 { margin: 6px 0 4px; font-size: 22px; font-weight: 800; }
    .meta { color: #64748b; font-size: 11px; }
    .hero-row { display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-top: 14px; }
    .risk-pill { text-align: center; min-width: 88px; padding: 10px 14px; border-radius: 12px; border: 1px solid #e2e8f0; background: #f8fafc; }
    .risk-pill strong { display: block; font-size: 28px; color: ${riskColor}; line-height: 1; }
    .risk-pill span { font-size: 9px; text-transform: uppercase; letter-spacing: .12em; color: #94a3b8; }
    .kpi-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px; margin: 16px 0; }
    .kpi { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px; background: #fafafa; text-align: center; }
    .kpi-label { font-size: 8px; font-weight: 700; text-transform: uppercase; color: #94a3b8; letter-spacing: .08em; }
    .kpi-value { font-size: 18px; font-weight: 800; margin-top: 4px; color: #0f172a; }
    .block { margin-bottom: 22px; }
    .page-break { page-break-before: always; padding-top: 8px; }
    .section-title { font-size: 11px; font-weight: 800; letter-spacing: .16em; text-transform: uppercase; color: #dc2626; margin: 0 0 12px; padding-bottom: 6px; border-bottom: 1px solid #fecaca; }
    .summary { padding: 14px 16px; border-radius: 10px; background: #f8fafc; border: 1px solid #e2e8f0; font-size: 13px; }
    .split-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; }
    .panel { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px; background: #fff; }
    .panel h3 { margin: 0 0 8px; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: .12em; color: #64748b; }
    .finding { padding: 8px 10px; border-radius: 8px; border: 1px solid #fde68a; background: #fffbeb; margin-bottom: 6px; font-size: 11px; }
    .decision { display: flex; gap: 10px; padding: 10px; border: 1px solid #e2e8f0; border-radius: 8px; margin-bottom: 6px; align-items: flex-start; }
    .priority { width: 32px; height: 32px; border-radius: 8px; display: inline-flex; align-items: center; justify-content: center; color: #fff; font-weight: 700; font-size: 10px; flex-shrink: 0; }
    .p1 { background: #dc2626; } .p2 { background: #ea580c; } .p3 { background: #64748b; }
    .decision-cat { display: block; font-size: 8px; font-weight: 700; text-transform: uppercase; color: #94a3b8; margin-bottom: 2px; }
    .decision p { margin: 0; font-size: 11px; }
    .insight-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
    .insight-card { border: 1px solid #e2e8f0; border-radius: 10px; padding: 10px 12px; background: #fafafa; }
    .insight-card h3 { margin: 0 0 6px; font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: .1em; color: #475569; }
    .insight-card ul { margin: 0; padding-left: 16px; }
    .insight-card li { margin-bottom: 4px; font-size: 11px; }
    .chart-panel { border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px; margin-bottom: 12px; background: #fafafa; }
    .chart-caption { font-size: 9px; font-weight: 700; text-transform: uppercase; letter-spacing: .12em; color: #64748b; margin: 0 0 8px; }
    .chart-row { display: grid; grid-template-columns: 88px 1fr 36px; align-items: center; gap: 8px; margin-bottom: 7px; font-size: 11px; }
    .chart-label { font-weight: 700; text-transform: uppercase; color: #475569; font-size: 10px; }
    .chart-track { height: 14px; background: #e2e8f0; border-radius: 6px; overflow: hidden; }
    .chart-bar { height: 100%; border-radius: 6px; min-width: 2px; }
    .chart-label-wide { font-weight: 600; font-size: 10px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .chart-value { text-align: right; font-weight: 700; color: #334155; }
    .data-table { width: 100%; border-collapse: collapse; font-size: 10px; }
    .data-table th, .data-table td { border: 1px solid #e2e8f0; padding: 7px 8px; text-align: left; vertical-align: top; }
    .data-table th { background: #f1f5f9; font-size: 9px; text-transform: uppercase; letter-spacing: .08em; color: #475569; font-weight: 700; }
    .data-table tbody tr:nth-child(even) { background: #f8fafc; }
    .table-note { font-size: 10px; color: #94a3b8; margin-top: 6px; }
    .ai { padding: 14px; border-radius: 10px; background: #f0fdfa; border: 1px solid #99f6e4; white-space: pre-wrap; font-size: 12px; }
    .data-hub-title { font-size: 14px; font-weight: 800; color: #0f172a; margin: 0 0 16px; }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .block { page-break-inside: avoid; }
    }
  </style>
</head>
<body>
  <div class="doc">
    <header class="hero">
      <div class="eyebrow">RAN Intelligence · ${escapeHtml(fr ? "Rapport post-import" : "Post-import report")}</div>
      <h1>${escapeHtml(snapshotDate)}</h1>
      <div class="meta">${escapeHtml(report.generated_at)} · Focus: ${escapeHtml(focus)}</div>
      <div class="hero-row">
        <div class="kpi-grid" style="flex:1;margin:0">
          ${kpiItems.map((kpi) => `<div class="kpi"><div class="kpi-label">${escapeHtml(kpi.label)}</div><div class="kpi-value">${kpi.value}</div></div>`).join("")}
        </div>
        <div class="risk-pill"><strong>${riskScore}</strong><span>${fr ? "Risque /100" : "Risk /100"}</span></div>
      </div>
    </header>

    ${htmlSectionBlock(fr ? "Resume executif" : "Executive summary", `<div class="summary">${escapeHtml(report.executive[lang])}</div>`)}

    ${
      findingsHtml || decisionsHtml || severityHtml
        ? htmlSectionBlock(
            fr ? "Synthese decisionnelle" : "Decision summary",
            `<div class="split-2">
              ${findingsHtml ? `<div class="panel"><h3>${fr ? "Analyses critiques" : "Critical findings"}</h3>${findingsHtml}</div>` : ""}
              ${decisionsHtml ? `<div class="panel"><h3>${fr ? "Recommandations" : "Recommendations"}</h3>${decisionsHtml}</div>` : ""}
              ${severityHtml ? `<div class="panel"><h3>${fr ? "Alertes par severite" : "Alerts by severity"}</h3>${severityHtml}</div>` : ""}
            </div>`,
          )
        : ""
    }

    ${report.sections.length ? htmlSectionBlock(fr ? "Analyse NOC" : "NOC analysis", htmlInsightCards(report.sections, lang)) : ""}

    ${aiText ? htmlSectionBlock(fr ? "Analyse IA" : "AI analysis", `<div class="ai">${escapeHtml(aiText)}</div>`) : ""}

    ${
      dataSections
        ? `<section class="block page-break"><p class="data-hub-title">${fr ? "Donnees importees" : "Imported data"}</p>${dataSections}</section>`
        : ""
    }
  </div>
  <script>window.onload = function(){ window.print(); };</script>
</body>
</html>`;

  const win = window.open("", "_blank");
  if (!win) return;
  win.document.open();
  win.document.write(html);
  win.document.close();
}
